/**
 * The widget catalogue as `engine/src/flyball/interfaces/server/widgets.json`: every type the
 * dashboard knows, with its config schema evaluated against an empty rig, so the rig-dependent
 * pickers reduce to their `x-binding`. Run `npm run widgets-json` after changing a widget.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Bindings } from "../apps/dashboard/src/dashboard/context.js";
import { CATEGORIES, WIDGET_TYPES } from "../apps/dashboard/src/widgets/registry.js";

const empty: Bindings = {
  devices: [],
  signals: [],
  controllers: [],
  deviceLabel: (name) => name,
  signalLabel: (address) => address,
  signalAt: () => undefined,
};

const catalogue = {
  source: "ui/apps/dashboard/src/widgets/*.tsx (WIDGET_TYPES in registry.ts); generated by ui/scripts/widgets-json.ts",
  bindings: {
    signal: "a signal address on this rig, e.g. blender.flows.dry",
    controller: "a controller's name: the address of the signal it drives",
    device: "a device's name",
  },
  categories: CATEGORIES,
  types: WIDGET_TYPES.map((t) => ({
    type: t.type,
    label: t.label,
    description: t.description,
    category: t.category,
    default_size: t.defaultSize,
    min_size: t.minSize,
    cost: t.cost,
    header: t.header ?? true,
    config: t.configSchema(empty, t.defaultConfig?.(empty) ?? {}),
    ...(t.uiSchema ? { ui: t.uiSchema } : {}),
  })),
};

const target = resolve(process.argv[2] ?? "../engine/src/flyball/interfaces/server/widgets.json");
writeFileSync(target, JSON.stringify(catalogue, null, 2) + "\n");
console.log(`${catalogue.types.length} widget types → ${target}`);
