/**
 * The widget catalogue as `engine/src/flyball/interfaces/server/widgets.json`: every kind the
 * dashboard knows, with its config schema evaluated against an empty rig, so the rig-dependent
 * pickers reduce to their `x-binding`. Run `npm run widgets-json` after changing a widget.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Bindings } from "../apps/dashboard/src/dashboard/context.js";
import { CATEGORIES, WIDGET_KINDS } from "../apps/dashboard/src/widgets/registry.js";

const empty: Bindings = {
  devices: [],
  signals: [],
  controllers: [],
  deviceLabel: (name) => name,
  signalLabel: (address) => address,
  signalAt: () => undefined,
};

const catalogue = {
  source: "ui/apps/dashboard/src/widgets/*.tsx (WIDGET_KINDS in registry.ts); generated by ui/scripts/widgets-json.ts",
  bindings: {
    signal: "a signal address on this rig, e.g. blender.flows.dry",
    controller: "a controller's name: the address of the signal it drives",
    device: "a device's name",
  },
  categories: CATEGORIES,
  kinds: WIDGET_KINDS.map((k) => ({
    kind: k.kind,
    label: k.label,
    description: k.description,
    category: k.category,
    default_size: k.defaultSize,
    min_size: k.minSize,
    cost: k.cost,
    header: k.header ?? true,
    config: k.configSchema(empty, k.defaultConfig?.(empty) ?? {}),
    ...(k.uiSchema ? { ui: k.uiSchema } : {}),
  })),
};

const target = resolve(process.argv[2] ?? "../engine/src/flyball/interfaces/server/widgets.json");
writeFileSync(target, JSON.stringify(catalogue, null, 2) + "\n");
console.log(`${catalogue.kinds.length} widget kinds → ${target}`);
