#!/usr/bin/env python3
"""Every registered driver's signals, by unit symbol and dimension -- auto, not hand-maintained.

Every `Output`/`Signal` a driver declares already carries a `Quantity`, and a `Quantity`
already carries its `Unit` (symbol) and the unit's `Dimension` (label) -- see
`flyball.foundation.quantities.Quantity`. So "search by unit" or "search by dimension" doesn't need
a hand-maintained field in `drivers-manifest.yaml`; it needs one read of what every driver
already declares. This script does that read: for each registered device whose class
builds with only a fake link (no real hardware, no extra required config), it builds one
instance and records each signal's `(name, unit_symbol, dimension)`.

Run: `uv run python scripts/index_signals.py` (from `linux/`). Prints YAML to stdout.
"""

from __future__ import annotations

import sys

import yaml
from flyball.foundation.device import DriverConfig, Readable
from flyball.model.catalog import Catalogs

LINK_CANDIDATES = ({"tag": "fake_i2c"}, {"tag": "fake_uart"})
"""Every driver here needs only a link to construct -- no scripted reply is read until
a signal is actually sampled, so an unscripted `FakeI2c`/`FakeUart` (empty replies) is
enough to build the device and inspect its signal tree."""


def try_build(tag: str, cls: type) -> Readable | None:
    if not (isinstance(cls, type) and issubclass(cls, DriverConfig)):
        return None
    for link_config in LINK_CANDIDATES:
        try:
            instance = cls.model_validate({"link": link_config})
        except Exception:
            continue
        try:
            device = instance.build(name=tag)
        except Exception:
            continue
        if isinstance(device, Readable):
            return device
    return None


def main() -> int:
    catalog = Catalogs()
    catalog.discover()
    entries: dict[str, list[dict[str, str]]] = {}
    skipped: list[str] = []
    for tag, cls in sorted(catalog.devices.items()):
        device = try_build(tag, cls)
        if device is None:
            skipped.append(tag)
            continue
        entries[tag] = [
            {"signal": name, "unit": signal.unit.symbol, "dimension": signal.unit.dimension.label}
            for name, signal in sorted(device.signals.items())
            if name not in ("conditions",)
        ]

    print("# Auto-generated by scripts/index_signals.py -- do not hand-edit.")
    print("# Built from a fake link (no real hardware); proves every driver's signal")
    print("# tree is introspectable for unit/dimension search without a manifest field.")
    yaml.safe_dump({"by_tag": entries}, sys.stdout, sort_keys=False, allow_unicode=True)
    print(f"\n# {len(entries)} drivers introspected; skipped (need real config beyond a")
    print(f"# fake link -- gpio-based/actuator drivers, mostly): {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
